version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api_back
  - source: /config/
    destination: /home/ubuntu/config
  - source: /.env
    destination: /home/ubuntu
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 300
      runas: ubuntu
      environment:
        PATH: /home/ubuntu/.nvm/versions/node/v18.20.4/bin:$PATH
