import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import Header from "./Header";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en" className="h-full">
        <body className={cn("h-full")}>
          <main>{children}</main>
          <Toaster />
        </body>
      </html>
    </ReactQueryProvider>
  );
}
